import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import { ContactTable } from "../components/ContactTable.jsx";
import { SearchBar } from "../components/SearchBar.jsx";
import { useState, useEffect, useMemo } from "react";
import { debounce } from "lodash";

const inter = Inter({ subsets: ["latin"] });

const defaultEndpoint = `https://rickandmortyapi.com/api/character/`;

export async function getServerSideProps() {
  const res = await fetch(defaultEndpoint);
  const data = await res.json();
  return {
    props: {
      data,
    },
  };
}

export default function Home({ data }) {
  const { info, results: defaultResults = [] } = data;
  const [results, updateResults] = useState(defaultResults);
  const [page, updatePage] = useState({
    ...info,
    current: defaultEndpoint,
  });
  const { current } = page;

  const handleSearchChange = (newValue) => {
    const endpoint = defaultEndpoint + `?name=${newValue}`;
    updatePage({
      current: endpoint,
    });
  };
  const debouncedHandleSearchChange = useMemo(
    () => debounce(handleSearchChange, 500),
    []
  );

  const fetchContacts = async () => {
    try {
      const res = await fetch(current);
      const nextData = await res.json();

      updatePage({
        current,
        ...nextData.info,
      });

      updateResults(nextData.results || []);
      return;

      {
        /* if (!nextData.info?.prev) {
        updateResults(nextData.results);
        return;
      }

      updateResults((prev) => {
        return [...prev, ...nextData.results];
      }); */
      }
    } catch (err) {
      console.log(err);
    }
  };

  const handleLoadNext = () => {
    updatePage((prev) => {
      return {
        ...prev,
        current: page?.next,
      };
    });
  };
  const handleLoadPrev = () => {
    updatePage((prev) => {
      return {
        ...prev,
        current: page?.prev,
      };
    });
  };

  useEffect(() => {
    if (current === defaultEndpoint) return;

    fetchContacts();
  }, [current]);

  return (
    <>
      <Head>
        <title>Contact Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.searchSection}>
          <h1>Contacts</h1>
          <SearchBar onChange={debouncedHandleSearchChange} />
        </div>
        <div className={styles.tableSection}>
          <ContactTable fetchedData={results} />
          <div className={styles.pageSection}>
            {page?.prev && <button onClick={handleLoadPrev}>Prev page</button>}
            {page?.next && <button onClick={handleLoadNext}>Next page</button>}
          </div>
        </div>
      </main>
    </>
  );
}
